### ISSUE TITLE
error on running the experiment test

### ISSUE THREAD

**Issue by Adnandut** [OuyangWenyu/torchhydro#10]
### Environment Information

-   torchhydro version: 0.0.8
-   Python version: 3.12.7
-   Operating System: windows 11

### Description

while running the experiment 
run_camelslstm_experiments.py
it gave me error 

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/sdc/owen/code/HydroFL/scripts/camels531.csv'

### What I Did

python run_camelslstm_experiments.py
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/sdc/owen/code/HydroFL/scripts/camels531.csv'

**Comment by OuyangWenyu** [comment]
You can just set the param gage_id_file as None. You can run this code with a debugging mode. Add some breakpoints and see how the code run step by step.

**Comment by OuyangWenyu** [comment]
use version 0.0.9 and update the packages hydrodataset and hydrodatasource to newest versions.
