### ISSUE TITLE
run_camelslstm_experiments.py 单位问题

### ISSUE THREAD

**Issue by Slmtdhy** [OuyangWenyu/torchhydro#8]
### Environment Information

-   torchhydro version:0.0.7
-   Python version:3.12
-   Operating System:Linux

### Description

run experiments/run_camelslstm_experiments.py 
ValueError: target unit should be a valid unit like 'mm/d’, 'mm/day', 'mm/h', 'mm/hour', 'mm/3h','mm/5d,

**Comment by OuyangWenyu** [comment]
use version 0.0.9 and update hydrodataset and hydrodatasource to the newest versions. This has been fixed.
